# port
server:
  port: 8081

# database settings
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/se?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Linhao01